---
glpi_version: '10.0.18'
glpi_archive_name: glpi-{{ glpi_version }}.tgz
glpi_download_url: https://github.com/glpi-project/glpi/releases/download/{{
  glpi_version }}/{{ glpi_archive_name }}
glpi_download_checksum: >-
  sha256:fe044e021c17ee88e088a8a4392c7807c9a0f397a1a551689d2eb7f668439e96

glpi_language: ru_RU

glpi_uid: 60000
glpi_gid: 60000

glpi_dir: /usr/share/glpi
glpi_cache_dir: /var/cache/glpi
glpi_config_dir: /etc/glpi
glpi_log_dir: /var/log/glpi
glpi_var_dir: /var/lib/glpi

glpi_db_crypt_file: secrets/glpicrypt.key
glpi_db_host: 127.0.0.1
glpi_db_user: root
glpi_db_password: ''
glpi_db_name: glpi
glpi_db_certs:
  ca_content: '{{ lookup("ansible.builtin.file", "secrets/CA.crt") }}'
  ca_file: '{{ glpi_config_dir }}/dbsslca.crt'
  cert_content: '{{ lookup("ansible.builtin.file",
    "secrets/{{ inventory_hostname }}.crt") }}'
  cert_file: '{{ glpi_config_dir }}/dbsslcert.crt'
  key_content: '{{ lookup("ansible.builtin.file",
    "secrets/{{ inventory_hostname }}.key") }}'
  key_file: '{{ glpi_config_dir }}/dbsslkey.key'

glpi_config:
  config_db: |
    <?php
    class DB extends DBmysql {
      public $dbhost = '{{ glpi_db_host }}';
      public $dbuser = '{{ glpi_db_user }}';
      public $dbpassword = '{{ glpi_db_password | urlencode }}';
      public $dbdefault = '{{ glpi_db_name }}';
      public $dbssl = true;
      public $dbsslca = '{{ glpi_db_certs.ca_file }}';
      public $dbsslcert = '{{ glpi_db_certs.cert_file }}';
      public $dbsslkey = '{{ glpi_db_certs.key_file }}';
      public $use_utf8mb4 = true;
      public $allow_myisam = false;
      public $allow_datetime = false;
      public $allow_signed_keys = false;
    }
  local_define: |
    <?php
    define('GLPI_VAR_DIR', '{{ glpi_var_dir }}');
    define('GLPI_LOG_DIR', '{{ glpi_log_dir }}');

glpi_config_attrs:
  config_db:
    owner: glpi
    group: glpi
    mode: '0600'
  config_db_slave:
    owner: glpi
    group: glpi
    mode: '0600'
...
