---
angie_httpd_conf_backend:
  backend: |
    server {
      listen 443 default_server reuseport ssl;
      listen [::]:443 default_server reuseport ssl;
      http2 on;

      ssl_certificate     {{ angie_web_cert.cert_path }};
      ssl_certificate_key {{ angie_web_cert.key_path }};

      root  {{ glpi_dir }}/public;

      location / {
        try_files $uri /index.php$is_args$args;
      }

      location ^~ /install {
        deny all;
      }

      location ~ ^/index\.php$ {
        fastcgi_pass unix:{{ php_fpm_sock }};

        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      }
    }
angie_httpd_conf: '{{ angie_httpd_conf_default | ansible.builtin.combine(
  angie_httpd_conf_status, angie_httpd_conf_backend )}}'
...
