---
tls_certs_certs:
  - ca_content: '{{ lookup("ansible.builtin.file", mariadb_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", mariadb_ca_key_path) }}'
    cert_path: '{{ mariadb_cert_path }}'
    key_path: '{{ mariadb_key_path }}'
...
