---
gencerts_ca_content: '{{ lookup("ansible.builtin.file",
  "secrets/CA.crt") }}'
gencerts_ca_privatekey_content: '{{ lookup("ansible.builtin.file",
  "secrets/CA.key") }}'
gencerts_common_name: '{{ inventory_hostname }}'
gencerts_extended_key_usage: [serverAuth, clientAuth]
gencerts_extended_key_usage_critical: false
gencerts_ignore_timestamps: false
gencerts_key_usage_critical: false
gencerts_key_usage: [digitalSignature, keyEncipherment]
gencerts_not_after: '21250101000000Z'
gencerts_not_before: '20250101000000Z'
gencerts_subject_alt_name:
  - 'DNS:{{ inventory_hostname_short }}'
  - 'DNS:localhost'
  - 'IP:127.0.0.1'
gencerts_use_common_name_for_san: false

gencerts_certs:
  - certificate_path: secrets/{{ inventory_hostname }}.crt
    privatekey_path: secrets/{{ inventory_hostname }}.key
...
