---
- name: Create certs and wait for connection
  hosts: all
  become: true
  gather_facts: false
  roles:
    - tls_ca
    - tls_certs
    - wait_connection
    - system_groups
    - system_users

- name: DB provision
  hosts: db
  become: true
  gather_facts: false
  roles:
    - mariadb
    - mariadb_timezones
    - mariadb_databases
    - mariadb_users

- name: Web provision
  hosts: [lb, backend]
  become: true
  gather_facts: false
  roles:
    - angie

- name: Backend provision
  hosts: backend
  become: true
  gather_facts: false
  roles:
    - php_fpm
    - glpi
...
