---
glpi_db_host: '{{ hostvars["db01"].ip_address }}'
glpi_db_user: glpi
glpi_db_password: '{{ lookup("ansible.builtin.password",
  "secrets/mariadb_glpi_password.txt", length=26) }}'
glpi_db_name: glpi
...
