---
tls_certs_certs:
  - ca_content: '{{ lookup("ansible.builtin.file", web_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", web_ca_key_path) }}'
    cert_path: '{{ web_cert_path }}'
    key_path: '{{ web_key_path }}'
    not_after: '{{ web_cert_not_after }}'
    not_before: '{{ web_cert_not_before }}'
...
