---
- name: Create directories for certs and keys
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: '{{ item }}'
    mode: '0755'
    state: directory
  loop: '{{ (tls_certs_certs | map(attribute="cert_path") +
             tls_certs_certs | map(attribute="key_path"))
    | map("ansible.builtin.dirname") | ansible.builtin.unique }}'

- name: Create private keys
  become: false
  delegate_to: localhost
  community.crypto.openssl_privatekey:
    path: '{{ item.key_path }}'
  loop: '{{ tls_certs_certs }}'
  no_log: '{{ not debug }}'

- name: Create certificate signing requests (CSRs)
  become: false
  delegate_to: localhost
  community.crypto.openssl_csr_pipe:
    common_name: '{{ item.common_name | default(tls_certs_common_name) }}'
    extended_key_usage: '{{ item.extended_key_usage |
      default(tls_certs_extended_key_usage) }}'
    extended_key_usage_critical: '{{ item.extended_key_usage_critical |
      default(tls_certs_extended_key_usage_critical) }}'
    key_usage: '{{ item.key_usage | default(tls_certs_key_usage) }}'
    key_usage_critical: '{{ item.key_usage_critical |
      default(tls_certs_key_usage_critical) }}'
    privatekey_path: '{{ item.key_path }}'
    subject_alt_name: '{{ item.subject_alt_name |
      default(tls_certs_subject_alt_name) }}'
    use_common_name_for_san: '{{ item.use_common_name_for_san |
      default(tls_certs_use_common_name_for_san) }}'
  changed_when: false
  loop: '{{ tls_certs_certs }}'
  no_log: '{{ not debug }}'
  register: tls_certs_csrs

- name: Create certificates from CSRs
  become: false
  delegate_to: localhost
  community.crypto.x509_certificate:
    csr_content: "{{ item.csr }}"
    ignore_timestamps: '{{ item.item.ignore_timestamps |
      default(tls_certs_ignore_timestamps) }}'
    ownca_content: '{{ item.item.ca_content |
      default(tls_certs_ca_content) }}'
    ownca_not_after: '{{ item.item.not_after |
      default(tls_certs_not_after) }}'
    ownca_not_before: '{{ item.item.not_before |
      default(tls_certs_not_before) }}'
    ownca_privatekey_content: '{{ item.item.ca_key_content |
      default(tls_certs_ca_key_content) }}'
    path: '{{ item.item.cert_path }}'
    privatekey_path: '{{ item.privatekey }}'
    provider: ownca
  loop: '{{ tls_certs_csrs.results }}'
  no_log: '{{ not debug }}'
...
