---
- name: Install GLPI service
  ansible.builtin.template:
    src: glpi.service
    dest: /etc/systemd/system/glpi.service
    owner: root
    group: root
    mode: '0755'

- name: Install GLPI timer
  ansible.builtin.template:
    src: glpi.timer
    dest: /etc/systemd/system/glpi.timer
    owner: root
    group: root
    mode: '0755'
  notify: Restart GLPI timer

- name: Enable and start GLPI timer
  ansible.builtin.systemd_service:
    name: glpi.timer
    daemon_reload: true
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
...
